version: "2"

linters:
  exclusions:
    paths:
      - pkg/queue/heap/heap.go
      - pkg/queue/heap/heap_test.go
      - pkg/queue/multischedulingqueue/multi_scheduling_queue.go

run:
  timeout: 10m