apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-queue-plugin-config
  namespace: koord-queue
data:
  plugin.yaml: |
{{ toYaml .Values.pluginConfigs | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-queue-jobextensions-config
  namespace: koord-queue
data:
  config.yaml: |
{{ toYaml .Values.extension.jobextensions.config | indent 4}}